
export const HIDE_ALERT = 'REMOVE_ALERT'

export const ADVANCE_TOTAL_VALUE = "ADVANCE_TOTAL_VALUE";

export const GROUP_TOTAL_VALUE = "GROUP_TOTAL_VALUE";

export const TOTAL_COST_VALUE = "TOTAL_COST_VALUE ";

export const ADVANCE_PRICE_INPUT_VALUE = "ADVANCE_PRICE_INPUT_VALUE"

export const GROUP_PRICE_INPUT_VALUE = "GROUP_PRICE_INPUT_VALUE";

export const INCREMENT_ADVANCE_VALUE = "INCREMENT_ADVANCE_VALUE"

export const DECREMENT_ADVANCE_VALUE = "DECREMENT_ADVANCE_VALUE";

export const INCREMENT_GROUP_VALUE = "INCREMENT_GROUP_VALUE";

export const DECREMENT_GROUP_VALUE = "DECREMENT_GROUP_VALUE";

export const SELECTED_TICKETS = "SELECTED_TICKETS";

export const HIDE_PAYMENT_PAGE = 'HIDE_PAYMENT_PAGE'

export const DISPLAY_PROCESSING_FEE = "DISPLAY_PROCESSING_FEE";  

export const HIDE_PROCESSING_FEE = "HIDE_PROCESSING_FEE";  

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const EMPTY_VALUES_ALERT = "EMPTY_VALUES_ALERT";

export const ONE_TICKET_ALERT = "ONE_TICKET_ALERT "; 
export const REGISTER_ALERT = 'REGISTER_ALERT';
export const LOGIN_ALERT = 'LOGIN_ALERT'; 

